### PR TITLE
Cart

### PR DESCRIPTION
**Pull request by JoshuaSkootsky**
Ability to add boats to cart - restored.

### CODE REVIEW

**Comment by natiwhitney** [comment]
Thanks for taking a look @JoshuaSkootsky 
But, we need to use the thunk for the logged in user because the update needs to be persisted in the database

Therefore, we need to use getUpdatedUserCart

**Comment by JoshuaSkootsky** [comment]
Here is an Imgur link to what the Cart looks like as a Material UI table with dummy buttons for plugging into thunks: https://imgur.com/a/OPVBBLq

**Comment by natiwhitney** [comment]
@JoshuaSkootsky can you also resolve the merge conflicts?

**Comment by JoshuaSkootsky** [comment]
@natiwhitney changes were made

**Pull request merged**
